steps:
  - id: 'Executando go install'
    name: 'gcr.io/cloud-builders/go'
    args: ['install', '-v','./...']
    env: ['PROJECT_ROOT=goServer']

  - id: 'Executando go unit test'
    name: 'gcr.io/cloud-builders/go'
    args: ['test', '-v', './...']
    env: ['PROJECT_ROOT=goServer']

  - id: "Gerando o build da aplicação"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/go-server', 'goServer']

  - id: "Executando o push da imagem no GCR"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/go-server']

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login --username=leorrodrigues --password=$$PASSWORD']
    secretEnv: ['PASSWORD']
  
  - id: "Executando o push da imagem no DockerHub"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'leorrodrigues/go-server']
  
secrets:
- kmsKeyName: projects/iniciando-ci/locations/global/keyRings/fullcycle/cryptoKeys/dockerhub-secret
  secretEnv:
    PASSWORD: 'CiQANp9r3fSspntKeW784LJ1TMMSCRwmzcQqj6ZGarlWTHr2GVoSOQBo6N+G8aDMcIuKhCBW4xPA
XqjAvZk/AO80a5+BC8pIv5eSjLmDHVyYSYACOWN69nfd92xXzZTnSA=='

images:
  - 'gcr.io/$PROJECT_ID/go-server'