steps:
  - id: 'Executando go install'
    name: 'gcr.io/cloud-builders/go'
    args: ['install', '-v','./...']
    env: ['PROJECT_ROOT=goServer']

  - id: 'Executando go unit test'
    name: 'gcr.io/cloud-builders/go'
    args: ['test', '-v', './...']
    env: ['PROJECT_ROOT=goServer']

  - id: "Gerando o build da aplicação"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=grc.io/$PROJECT_ID/go-server', 'goServer/']

images:
  - 'grc.io/$PROJECT_ID/go-server'