apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
spec:
  selector:
    matchLabels:
      app: mysql-server
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
      - name: mysql-server
        image: mysql:5.7
        args:
        - "--ignore-db-dir=lost+found"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-storage
      
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
            claimName: mysql-volume